#############################################################################
# Makefile for building: openni
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? 5? 17 15:03:32 2018
# Project:  openni.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.8.7/bin/qmake -o Makefile openni.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.8.7/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.8.7/include/QtCore -I/usr/local/Trolltech/Qt-4.8.7/include -I/home/victor/software/opencv-3.1.0\include/\opencv -I/home/victor/software/opencv-3.1.0\include/\opencv2 -I/home/victor/software/opencv-3.1.0\include/ -I../../software/OpenNI-Linux-x64-2.3/Include -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.8.7/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.8.7/lib /home/victor/software/opencv-3.1.0/build/lib/\libopencv*.so /home/victor/software/OpenNI-Linux-x64-2.3/Redist/\libOpenNI2.so -lQtCore -L/usr/local/Trolltech/Qt-4.8.7/lib -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.8.7/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = /usr/local/Trolltech/Qt-4.8.7/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/shared.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/include_source_dir.prf \
		openni.pro
QMAKE_TARGET  = openni
DESTDIR       = 
TARGET        = openni

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: openni.pro  /usr/local/Trolltech/Qt-4.8.7/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.8.7/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/shared.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.8.7/lib/libQtCore.prl
	$(QMAKE) -o Makefile openni.pro
/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/shared.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.8.7/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile openni.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/openni1.0.0 || $(MKDIR) .tmp/openni1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/openni1.0.0/ && $(COPY_FILE) --parents main.cpp .tmp/openni1.0.0/ && (cd `dirname .tmp/openni1.0.0` && $(TAR) openni1.0.0.tar openni1.0.0 && $(COMPRESS) openni1.0.0.tar) && $(MOVE) `dirname .tmp/openni1.0.0`/openni1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/openni1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

